resources:
  - git::https://repo1.dso.mil/platform-one/big-bang/bigbang.git//base/flux/?ref=1.45.0
  - git::https://repo1.dso.mil/platform-one/big-bang/bigbang.git//base/?ref=1.45.0
  - start.yaml

configMapGenerator:
  - name: common
    namespace: bigbang
    behavior: merge
    files:
      - values.yaml

secretGenerator:
  - name: common-bb
    namespace: bigbang
    behavior: merge
    files:
      - values.yaml=common-bb.enc.yaml

patchesStrategicMerge:
- |-
  apiVersion: source.toolkit.fluxcd.io/v1beta2
  kind: GitRepository
  metadata:
    name: bigbang
    namespace: bigbang
  spec:
    ref:
      $patch: replace
      tag: "1.45.0"
