registryCredentials:
  registry: registry1.dso.mil
  username: "registry1 username"
  password: "registry1 token"
  email: "registry1 email"
networkPolicies:
  enabled: false
istio:
  enabled: true
istiooperator:
  enabled: true
jaeger:
  enabled: false
kiali:
  enabled: false
clusterAuditor:
  enabled: false
gatekeeper:
  enabled: false
logging:
  enabled: false
eckoperator:
  enabled: false
fluentbit:
  enabled: false
monitoring:
  enabled: false
twistlock:
  enabled: false
addons:
  metricsServer:
    enabled: false
  minio:
    enabled: true
    values:
      tenant:
        pools:
          - servers: 1
            volumesPerServer: 1
