hostname: bigbang.dev

# Tune flux for dev
flux:
  interval: 1m
  rollback:
    cleanupOnFail: false

monitoring:
  enabled: false

logging:
  enabled: false
  # Directly modify chart values for dev workloads
  values:
    elasticsearch:
      master:
        count: 1
        resources:
          limits:
            cpu: 1
            memory: 3Gi
      data:
        count: 1
        persistence:
          storageClassName: ""
          size: 5Gi
        resources:
          limits:
            cpu: 1
            memory: 3Gi

istio:
  enabled: true
  # Directly modify chart values for dev workloads
  values:
    kiali:
      dashboard:
        auth:
          strategy: "anonymous"   
    ingressGateway:
      maxReplicas: 1
      serviceAnnotations:
        # Ensure mission apps have internal load balancer only
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
        # Enable cross zone load balancing
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

gatekeeper:
  enabled: false
  # Directly modify chart values for dev workloads
  values:
    replicas: 1

clusterAuditor:
  enabled: false
  
twistlock:
  enabled: false
  # Directly modify chart values for dev workloads
  values:
    console:
      persistence:
        size: 5Gi

addons:
  gitlab:
      enabled: true
      sso:
        enabled: false
      values:
        global:
          rails:
            bootstrap:
              enabled: false
          edition: ce
        gitlab-runner:
          resources:
            requests:
              cpu: 10m
            limits: {}
        gitlab:
          webservice:
            minReplicas: 1
            maxReplicas: 1
          sidekiq:
            minReplicas: 1
            maxReplicas: 1
          gitlab-shell:
            minReplicas: 1
            maxReplicas: 1
          gitaly:
            resources:
              requests:
                cpu: 50m
              limits: {}
          shared-secrets:
            resources:
              requests:
                cpu: 10m
              limits: {}
          migrations:
            resources:
              requests:
                cpu: 10m
              limits: {}
          task-runner:
            resources:
              requests:
                cpu: 10m
              limits: {}
        registry:
          hpa:
            minReplicas: 1
            maxReplicas: 1
        postgresql:
          metrics:
            resources:
              requests:
                cpu: 10m
              limits: {}
        minio:
          resources:
            requests:
              cpu: 50m
            limits: {}