# This is a basic workflow to help you get started with Actions

name: Deploy bigbang with k3d

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install k3d
        run: |
          export registry1_user="${{ secrets.BBUSER }}"
          export registry1_token="${{ secrets.BBPASS }}"
          export registry1_email="${{ secrets.BBUSER }}@email.com"
          sudo apt-get install curl
          curl -LOs https://github.com/rancher/k3d/releases/download/v5.4.6/k3d-linux-amd64
          sudo mv k3d-linux-amd64 /usr/local/bin/k3d
          sudo chmod a+xr /usr/local/bin/k3d
          curl -LOs "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo mv kubectl /usr/local/bin/kubectl
          sudo chmod a+xr /usr/local/bin/kubectl
          curl -LOs https://github.com/mikefarah/yq/releases/download/v4.29.2/yq_linux_amd64
          sudo mv yq_linux_amd64 /usr/local/bin/yq
          sudo chmod a+xr /usr/local/bin/yq
          k3d cluster create --k3s-arg "--disable=traefik@server:0" -p 80:80@loadbalancer -p 443:443@loadbalancer
          kubectl create namespace flux-system
          kubectl create secret docker-registry private-registry  --docker-server="registry1.dso.mil" --docker-username="$registry1_user" --docker-password="$registry1_token" --docker-email="$registry1_email" -n flux-system
          kubectl apply -k "https://repo1.dso.mil/platform-one/big-bang/bigbang.git//base/flux?ref=master"
          kubectl create namespace bigbang
          curl -sO https://repo1.dso.mil/platform-one/big-bang/bigbang/-/raw/master/chart/ingress-certs.yaml
          yq ea '. as $item ireduce ({}; . * $item )' bigbang/values.yaml  ingress-certs.yaml > values-merged.yaml
          yq  '.registryCredentials.username = strenv(registry1_user) | .registryCredentials.password = strenv(registry1_token) | .registryCredentials.email = strenv(registry1_email)' values-merged.yaml >  values-filled.yaml
          kubectl create secret generic terraform -n bigbang --from-file=values.yaml=values-filled.yaml
          kubectl apply -k "https://repo1.dso.mil/platform-one/big-bang/bigbang.git//base?ref=main"
          echo "${{ secrets.AGEKEY }}" | kubectl create secret generic sops-age --namespace=flux-system --from-file=age.agekey=/dev/stdin
          kubectl get deploy -o name -n flux-system | xargs -n1 -t kubectl rollout status -n flux-system
          kubectl wait kustomization environment --for=condition=Ready=true  -n bigbang --timeout=300s
          kubectl wait hr bigbang --for=condition=Ready=true  -n bigbang --timeout=300s
          kubectl wait hr istio --for=condition=Ready=true  -n bigbang --timeout=300s
          kubectl wait hr minio --for=condition=Ready=true  -n bigbang --timeout=300s
          kubectl get hr,po,svc -A
      - name: Verify ingress connects
        run: |
          curl -v https://minio.localhost.direct
          
