# This is a basic workflow to help you get started with Actions

name: Deploy bigbang with kind

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install kind
        run: |
          sudo apt-get update
          sudo apt-get install curl unzip
          curl -OL https://github.com/kubernetes-sigs/kind/releases/download/v0.11.1/kind-linux-amd64
          sudo mv kind-linux-amd64 /usr/local/bin/kind
          sudo chmod a+xr /usr/local/bin/kind
          curl -OL https://releases.hashicorp.com/terraform/1.0.4/terraform_1.0.4_linux_amd64.zip
          unzip terraform_1.0.4_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          sudo chmod a+xr /usr/local/bin/terraform 
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo mv kubectl /usr/local/bin/kubectl
          sudo chmod a+xr /usr/local/bin/kubectl
          kind create cluster
          kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/master/manifests/namespace.yaml
          kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)" 
          kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/master/manifests/metallb.yaml
          kubectl apply -f https://kind.sigs.k8s.io/examples/loadbalancer/metallb-configmap.yaml
          kubectl rollout status deployment.apps/controller -n metallb-system
          cat << EOF > terraform.tfvars
          registry1_username="${{ secrets.BBUSER }}"
          registry1_password="${{ secrets.BBPASS }}"
          EOF
          terraform init -input=false
          terraform apply -input=false -auto-approve
          kubectl get hr,po -A
      - name: Verify ingress connects
        run: |
          IP=$(hostname -i |  head -n1 | cut -d " " -f1)
          curl -svk --resolve minio.bigbang.dev:443:$IP https://minio.bigbang.dev
