# This is a basic workflow to help you get started with Actions

name: Deploy bigbang with kind

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install kind
        run: |
          sudo apt-get update
          sudo apt-get install curl unzip
          curl -OL https://github.com/kubernetes-sigs/kind/releases/download/v0.17.0/kind-linux-amd64
          sudo mv kind-linux-amd64 /usr/local/bin/kind
          sudo chmod a+xr /usr/local/bin/kind
          curl -OL https://releases.hashicorp.com/terraform/1.3.3/terraform_1.3.3_linux_amd64.zip
          unzip terraform_1.3.3_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          sudo chmod a+xr /usr/local/bin/terraform 
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo mv kubectl /usr/local/bin/kubectl
          sudo chmod a+xr /usr/local/bin/kubectl
          cat <<EOF | kind create cluster --config=-
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
          - role: control-plane
            kubeadmConfigPatches:
            - |
              kind: InitConfiguration
              nodeRegistration:
                kubeletExtraArgs:
                  node-labels: "ingress-ready=true"
            extraPortMappings:
            - hostPort: 80
              containerPort: 80
              listenAddress: "127.0.0.1"
              protocol: TCP
            - hostPort: 443
              containerPort: 443
              listenAddress: "127.0.0.1"
              protocol: TCP
          EOF
          kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-frr.yaml
          kubectl rollout status deployment/controller -n metallb-system --timeout 120s
          kubectl rollout status daemonset/speaker -n metallb-system --timeout 120s
          kubectl apply -f https://kind.sigs.k8s.io/examples/loadbalancer/metallb-config.yaml
          EOF
          cat << EOF > terraform.tfvars
          registry1_username="${{ secrets.BBUSER }}"
          registry1_password="${{ secrets.BBPASS }}"
          EOF
          terraform init -input=false
          terraform apply -input=false -auto-approve
          cat "${{ secrets.AGEKEY }}" | kubectl create secret generic sops-age --namespace=flux-system --from-file=age.agekey=/dev/stdin
          kubectl get deploy -o name -n flux-system | xargs -n1 -t kubectl rollout status -n flux-system
          kubectl wait kustomization environment --for=condition=Ready=true  -n bigbang --timeout=300s
          kubectl wait hr bigbang --for=condition=Ready=true  -n bigbang --timeout=300s
          kubectl wait hr istio --for=condition=Ready=true  -n bigbang --timeout=300s
          kubectl wait hr kiali --for=condition=Ready=true  -n bigbang  --timeout=600s
          while : ; do
            kubectl wait po --for=condition=Ready=true  -l app=public-ingressgateway -n istio-system --timeout=60s && break
            sleep 5
          done
          kubectl get hr,po,svc -A
      - name: Verify ingress connects
        run: |
          curl -v https://kiali.localhost.direct
